# Generated by Django 5.1.3 on 2024-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_payment_status_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('unpaid', 'No Pagado')], default='unpaid', max_length=20),
        ),
    ]
