# Generated by Django 5.1.3 on 2024-11-18 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0003_alter_client_id_alter_vet_id_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Programada'), ('Completed', 'Completada'), ('Cancelled', 'Cancelada')], default='Scheduled', max_length=20),
        ),
    ]
